repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
  # - repo: https://github.com/pycqa/pylint
  #   rev: 'v2.11.1'
  #   hooks:
  #   -   id: pylint
  - repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
      - id: black
        name: Run black formatter
        language_version: python3.7
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        additional_dependencies: [toml]
        name: Sort imports using isort
  - repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
